# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#✅ 상수
APP_NAME = ENV["APP_NAME"]
WIDGET_NAME = ENV["WIDGET_NAME"]

PRD_SCHEME = ENV["PRD_SCHEME"]
DEV_SCHEME = ENV["DEV_SCHEME"]
BUNDLE_ID = ENV["BUNDLE_ID"]
WIDGET_BUNDLE_ID = ENV["WIDGET_BUNDLE_ID"]

APP_STORE_CONNECT_API_KEY_KEY_ID = ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"]
APP_STORE_CONNECT_API_KEY_ISSUER_ID = ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"]
APP_STORE_CONNECT_API_KEY_KEY = ENV["APP_STORE_CONNECT_API_KEY_KEY"]

KEYCHAIN_NAME = ENV["KEYCHAIN_NAME"]
KEYCHAIN_PASSWORD = ENV["KEYCHAIN_PASSWORD"]
P12_PASSWORD =ENV["P12_PASSWORD"]

PROJECT_PATH = ENV["PROJECT_PATH"]
TEAM_ID = ENV["TEAM_ID"]
APPLE_ID = ENV["APPLE_ID"]
PROFILE_PATH = ENV["PROFILE_PATH"]
SLACK_HOOK_URL = ENV["SLACK_HOOK_URL"]


default_platform(:ios)

platform :ios do


  lane :github_action_stg_upload_testflight do |options|
    api_key = app_store_connect_api_key(
      key_id: "#{APP_STORE_CONNECT_API_KEY_KEY_ID}",
      issuer_id: "#{APP_STORE_CONNECT_API_KEY_ISSUER_ID}",
      key_content: "#{APP_STORE_CONNECT_API_KEY_KEY}",
      is_key_content_base64: true,
      in_house: false
    )
    
    setup_ci

    match(
      storage_mode: "git",
      type: "appstore",
      app_identifier: ["com.5ing.bibbi","com.5ing.bibbi.widget"],
      readonly: is_ci,
      git_basic_authorization: Base64.strict_encode64("Do-hyun-Kim:#{ENV["MATCH_PERSONAL_TOKEN"]}"),
      generate_apple_certs: false
    )

    build_num = app_store_build_number(
      api_key: api_key,
      live: false
    )

    new_build_number = build_num + 1


    increment_build_number(
      xcodeproj: "14th-team5-iOS/App/App.xcodeproj",
      build_number: new_build_number
    )

    update_project_team(
      path: "14th-team5-iOS/App/App.xcodeproj",
      teamid: "#{TEAM_ID}"
    )



    build_app(
      workspace: "Bibbi.xcworkspace",
      scheme: "#{DEV_SCHEME}",
      export_method: "app-store",
      xcodebuild_formatter: "xcpretty",
      archive_path: "./build/Runner.xcarchive",
      output_directory: "./build/Runner",
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.5ing.bibbi" => "match AppStore com.5ing.bibbi",
          "com.5ing.bibbi.widget" => "match AppStore com.5ing.bibbi.widget"
        }
      }
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)


    slack(
      message: "⭐️ 테스트 플라이트 업로드 성공",
      channel: "#알림-ios-배포",
      slack_url: "#{SLACK_HOOK_URL}",
      username: "대신 배포해주는 고양이",
      icon_url: "https://avatars.githubusercontent.com/u/21079970?v=4",
      payload: {
        "Build Date" => Time.new.to_s,
      },
      attachment_properties: {
        fields: [
          {
            title: "Scheme",
            value: "#{DEV_SCHEME}",
          },
          {
            title: "Build Number",
            value: "#{new_build_number.to_s}",
          }
        ]
      },
      success: true
    )

  end


  lane :github_action_prd_upload_testflight do |options|
    api_key = app_store_connect_api_key(
      key_id: "#{APP_STORE_CONNECT_API_KEY_KEY_ID}",
      issuer_id: "#{APP_STORE_CONNECT_API_KEY_ISSUER_ID}",
      key_content: "#{APP_STORE_CONNECT_API_KEY_KEY}",
      is_key_content_base64: true,
      in_house: false
    )
    
    setup_ci

    match(
      storage_mode: "git",
      type: "appstore",
      app_identifier: ["com.5ing.bibbi","com.5ing.bibbi.widget"],
      readonly: is_ci,
      git_basic_authorization: Base64.strict_encode64("Do-hyun-Kim:#{ENV["MATCH_PERSONAL_TOKEN"]}"),
      generate_apple_certs: false
    )

    build_num = app_store_build_number(
      api_key: api_key,
      live: false
    )

    new_build_number = build_num + 1

    version = get_version_number(
      xcodeproj: "14th-team5-iOS/App/App.xcodeproj",
      target: "#{PRD_SCHEME}"
    )


    increment_build_number(
      xcodeproj: "14th-team5-iOS/App/App.xcodeproj",
      build_number: new_build_number
    )

    update_project_team(
      path: "14th-team5-iOS/App/App.xcodeproj",
      teamid: "#{TEAM_ID}"
    )



    build_app(
      workspace: "Bibbi.xcworkspace",
      scheme: "#{PRD_SCHEME}",
      export_method: "app-store",
      xcodebuild_formatter: "xcpretty",
      archive_path: "./build/Runner.xcarchive",
      output_directory: "./build/Runner",
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.5ing.bibbi" => "match AppStore com.5ing.bibbi",
          "com.5ing.bibbi.widget" => "match AppStore com.5ing.bibbi.widget"
        }
      }
    )

    download_dsyms(
      app_identifier: "com.5ing.bibbi",
      version: version,
      build_number: new_build_number,
      output_directory: "./14th-team5-iOS"
    )

    upload_symbols_to_crashlytics(
      gsp_path: "14th-team5-iOS/App/Resources/GoogleService-Info.plist"
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)


    slack(
      message: "⭐️ 테스트 플라이트 업로드 성공",
      channel: "#알림-ios-배포",
      slack_url: "#{SLACK_HOOK_URL}",
      username: "대신 배포해주는 고양이",
      icon_url: "https://avatars.githubusercontent.com/u/21079970?v=4",
      payload: {
        "Build Date" => Time.new.to_s,
      },
      attachment_properties: {
        fields: [
          {
            title: "Scheme",
            value: "#{PRD_SCHEME}",
          },
          {
            title: "Build Number",
            value: "#{new_build_number.to_s}",
          }
        ]
      },
      success: true
    )

  end





  #✅ 테스트 플라이트에 PRD 업로드
  lane :upload_prd_to_testflight do |options|
    app_store_connect_api_key(
      key_id: "#{APP_STORE_CONNECT_API_KEY_KEY_ID}",
      issuer_id: "#{APP_STORE_CONNECT_API_KEY_ISSUER_ID}",
      key_content: "#{APP_STORE_CONNECT_API_KEY_KEY}",
      is_key_content_base64: true,
      in_house: false
    )

    new_build_number = latest_testflight_build_number() + 1

    increment_build_number(
      xcodeproj: "#{PROJECT_PATH}",
      build_number: new_build_number
    )

    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{PRD_SCHEME}",
      export_method: "app-store",
      export_options: {
        method: "app-store", 
	provisioningProfiles: {
      "com.5ing.bibbi" => "match AppStore com.5ing.bibbi",
      "com.5ing.bibbi.widget" => "match AppStore com.5ing.bibbi.widget",
        }
      }
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)

    slack(
      message: "⭐️ 테스트 플라이트 업로드 성공",
      channel: "#알림-ios-배포",
      slack_url: "#{SLACK_HOOK_URL}",
      username: "대신 배포해주는 고양이",
      icon_url: "https://avatars.githubusercontent.com/u/21079970?v=4",
      payload: {
        "Build Date" => Time.new.to_s,
      },
      attachment_properties: {
        fields: [
          {
            title: "Scheme",
            value: "#{PRD_SCHEME}",
          },
          {
            title: "Build Number",
            value: "#{new_build_number.to_s}",
          }
        ]
      },
      success: true
    )    
  end

  #✅ 테스트 플라이트에 STG 업로드
  lane :upload_stg_to_testflight do |options|
    app_store_connect_api_key(
      key_id: "#{APP_STORE_CONNECT_API_KEY_KEY_ID}",
      issuer_id: "#{APP_STORE_CONNECT_API_KEY_ISSUER_ID}",
      key_content: "#{APP_STORE_CONNECT_API_KEY_KEY}",
      is_key_content_base64: true,
      in_house: false
    )

    new_build_number = latest_testflight_build_number() + 1

    increment_build_number(
      xcodeproj: "#{PROJECT_PATH}",
      build_number: new_build_number
    )

    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{DEV_SCHEME}",
      export_method: "app-store",
      export_options: {
        method: "app-store", 
	provisioningProfiles: {
      "com.5ing.bibbi" => "match AppStore com.5ing.bibbi",
      "com.5ing.bibbi.widget" => "match AppStore com.5ing.bibbi.widget",
        }
      }
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)

    slack(
      message: "⭐️ 테스트 플라이트 업로드 성공",
      channel: "#알림-ios-배포",
      slack_url: "#{SLACK_HOOK_URL}",
      username: "Bibbibot",
      icon_url: "https://avatars.githubusercontent.com/u/160627812?s=200&v=4",
      payload: {
        "Build Date" => Time.new.to_s,
      },
      attachment_properties: {
        fields: [
          {
            title: "Scheme",
            value: "#{DEV_SCHEME}",
          },
          {
            title: "Build Number",
            value: "#{new_build_number.to_s}",
          }
        ]
      },
      success: true
    )        
  end




  #🔴 예외 처리
  error do |lane, exception, options|
    slack(
      message: "❗️ 테스트 플라이트 업로드 실패",
      channel: "#알림-ios-배포",
      slack_url: "#{SLACK_HOOK_URL}",
      username: "대신 배포해주는 고양이",
      icon_url: "https://avatars.githubusercontent.com/u/21079970?v=4",
      success: false,
      attachment_properties: {
        fields: [
          {
            title: "Error message",
            value: "#{exception.to_s}",
            short: false
          }
        ]
      },
    )        
  end
end
