name: Bibbi

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
      - develop
    types:
      - closed
  
jobs:  
  build:
    runs-on: macos-13
    strategy:
      matrix:
        xcodebuild-scheme: ['App']
        
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '3.2.0'


      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '15.0'
            
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bring Bibbi ignored file with Config
        uses: actions/checkout@v3
        with: 
          repository: depromeet/14th-team5-iOS-ignored
          path: depromeet/14th-team5-iOS/14th-team5-iOS/XCConfig
          token: ${{secrets.ACTION_TOKEN}}
        
      - name: Install Tuist CLI
        run: brew install tuist
        
      - name: Install FastLane 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
      - run: brew install fastlane

      - name: Tuist Clean Command
        run: tuist clean
      
      - name: Tuist Fetch Command
        run: tuist install

      - name: Tuist Generate Commnad
        run: tuist generate
        
      - name: fastlane upload_prd_testflight
        if: ${{ github.base_ref == 'release' && github.event_name == 'push' }}
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          MATCH_PERSONAL_TOKEN: ${{ secrets.MATCH_PERSONAL_TOKEN}}
          PRD_SCHEME: ${{secrets.PRD_SCHEME}}
          BUNDLE_ID: ${{secrets.BUNDLE_ID}}
          SLACK_HOOK_URL: ${{secrets.SLACK_HOOK_URL}}
          WIDGET_BUNDLE_ID: ${{secrets.WIDGET_BUNDLE_ID}}
          PROFILE_PATH: ${{secrets.PROFILE_PATH}}
          APP_NAME: ${{secrets.APP_NAME}}
          APPLE_ID: ${{secrets.APPLE_ID}}
          TEAM_ID: ${{secrets.TEAM_ID}}
          WIDGET_NAME: ${{secrets.WIDGET_NAME}}
        run: fastlane github_action_prd_upload_testflight


      - name: fastlane upload_stg_testflight
        if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' }}
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          SLACK_HOOK_URL: ${{secrets.SLACK_HOOK_URL}}
          MATCH_PERSONAL_TOKEN: ${{ secrets.MATCH_PERSONAL_TOKEN}}
          DEV_SCHEME: ${{secrets.DEV_SCHEME}}
          BUNDLE_ID: ${{secrets.BUNDLE_ID}}
          WIDGET_BUNDLE_ID: ${{secrets.WIDGET_BUNDLE_ID}}
          PROFILE_PATH: ${{secrets.PROFILE_PATH}}
          APP_NAME: ${{secrets.APP_NAME}}
          APPLE_ID: ${{secrets.APPLE_ID}}
          TEAM_ID: ${{secrets.TEAM_ID}}
          WIDGET_NAME: ${{secrets.WIDGET_NAME}}
        run: fastlane github_action_stg_upload_testflight

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
